### ISSUE TITLE
Много инитов - плохо, нужен 1

### ISSUE THREAD

**Issue by koretskyhub** [go-park-mail-ru/2018_2_42#12]
https://github.com/go-park-mail-ru/2018_2_42/blob/c238175066f49f3363b7fc21bf57e2064596c892/authorization_server/accessor/insert.go#L111

**Comment by OlegSchwann** [comment]
[Собрал все инициализирующие функции в пучок.](https://github.com/go-park-mail-ru/2018_2_42/blob/85a946b7bcecc5886d3349296443ca0fa770d384/authorization_server/accessor/insert.go#L41) Они теперь вызываются из main.
