### ISSUE TITLE
РК 1

### ISSUE THREAD

**Issue by DmitryDorofeev** [go-park-mail-ru/2018_2_42#3]
- [x] хендлеры в отдельный пакет (0)

- [x] хардкод доступов к бд

- [x] перенести api doc в swagger (2)

**Comment by OlegSchwann** [comment]
Рефакторинг закончен.  
[Реализовал конфиг.](https://github.com/go-park-mail-ru/2018_2_42/commit/521a8406e41739c8952293abfca4a2ab47f61d58)  
[Добавил документацию.](https://github.com/go-park-mail-ru/2018_2_42/commit/ae525465fc035ae0a763fe5ecc9e47c587b2d1cc)  
[Перенёс обработчики в отдельный пакет.](https://github.com/go-park-mail-ru/2018_2_42/commit/532ed98b90830cdb81fc7f360e74536bde6694b3)
