### ISSUE TITLE
Вызывать из sql файла

### ISSUE THREAD

**Issue by koretskyhub** [go-park-mail-ru/2018_2_42#8]
https://github.com/go-park-mail-ru/2018_2_42/blob/c238175066f49f3363b7fc21bf57e2064596c892/authorization_server/accessor/insert.go#L50

**Comment by OlegSchwann** [comment]
Вынес инициализацию в отдельный файл. [Удалил лишнее.](https://github.com/go-park-mail-ru/2018_2_42/commit/ef507715ba85496481c1542eeb40246b10a324e1)
